### ISSUE TITLE
"Too many open files" 

### ISSUE THREAD

**Issue by ceremcem** [stephenhutchings/jade-static-brunch#4]
If there are jade files opened in text editor, it refuses to compile. I need to close - sometimes some, sometimes all - opened `.jade` files, even sometimes have to close all files in the project.

**Comment by ceremcem** [comment]
This issue happened again, here is the traceback: 

``` js
$ brunch build
path is:  app/test.jade
path is:  app/static/brunch.jade
path is:  app/static/mixins.jade
path is:  app/static/mypage.jade
path is:  app/static/ractive.jade

fs.js:443
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^
Error: EMFILE, too many open files 'public/ractive.html'
  at Object.fs.openSync (fs.js:443:18)
  at Object.fs.writeFileSync (fs.js:982:15)
  at /home/ceremcem/aktos-dcs-apps/aktos-website/node_modules/jade-static-brunch/index.js:58:12
  at /home/ceremcem/aktos-dcs-apps/aktos-website/node_modules/jade-static-brunch/node_modules/mkdirp/index.js:48:26
  at Object.oncomplete (fs.js:108:15)

```

**Comment by ceremcem** [comment]
Seems fixed by: https://github.com/stephenhutchings/jade-static-brunch/pull/1

Edit: 

It's not related with that pull request. 

But, the interesting point is, `brunch watch` or `brunch build` refuses to build but if you insist and try to compile again and again, it compiles.

**Comment by stephenhutchings** [comment]
Let me know the status of this now that #1 is merged.

**Comment by ceremcem** [comment]
After #1 this error seems to appear less frequent, but I can't say that it fixed the problem.

**Comment by nmccready** [comment]
@ceremcem gulp has this issue from time to time, bump up your machines ulimits. 

https://rtcamp.com/tutorials/linux/increase-open-files-limit/

**Comment by ceremcem** [comment]
`ulimit` helps till a point, but it doesn't solve my problem. So I changed the code a bit: https://github.com/stephenhutchings/jade-static-brunch/pull/5

**Comment by nmccready** [comment]
@ceremcem still he is not going to accept your PR, you need to PR to the root jade project first as that is the main fix.
